UPDATE static_territories SET tr_name_sk='Afrika' WHERE tr_iso_nr='2';
UPDATE static_territories SET tr_name_sk='Ázia' WHERE tr_iso_nr='142';
UPDATE static_territories SET tr_name_sk='Austrália a Nový Zéland' WHERE tr_iso_nr='53';
UPDATE static_territories SET tr_name_sk='Európa' WHERE tr_iso_nr='150';
UPDATE static_territories SET tr_name_sk='Karibik' WHERE tr_iso_nr='29';
UPDATE static_territories SET tr_name_sk='Melanézia' WHERE tr_iso_nr='54';
UPDATE static_territories SET tr_name_sk='Mikronézia' WHERE tr_iso_nr='57';
UPDATE static_territories SET tr_name_sk='Stredná Amerika' WHERE tr_iso_nr='13';
UPDATE static_territories SET tr_name_sk='Severná, Stredná a Južná Amerika' WHERE tr_iso_nr='19';
UPDATE static_territories SET tr_name_sk='Severná Afrika' WHERE tr_iso_nr='15';
UPDATE static_territories SET tr_name_sk='Severná Amerika' WHERE tr_iso_nr='21';
UPDATE static_territories SET tr_name_sk='Severná Európa' WHERE tr_iso_nr='154';
UPDATE static_territories SET tr_name_sk='Východná Afrika' WHERE tr_iso_nr='14';
UPDATE static_territories SET tr_name_sk='Východná Ázia' WHERE tr_iso_nr='30';
UPDATE static_territories SET tr_name_sk='Východná Európa' WHERE tr_iso_nr='151';
UPDATE static_territories SET tr_name_sk='Oceánia' WHERE tr_iso_nr='9';
UPDATE static_territories SET tr_name_sk='Polynézia' WHERE tr_iso_nr='61';
UPDATE static_territories SET tr_name_sk='Južná Afrika' WHERE tr_iso_nr='18';
UPDATE static_territories SET tr_name_sk='Južná Amerika' WHERE tr_iso_nr='5';
UPDATE static_territories SET tr_name_sk='Južná Ázia' WHERE tr_iso_nr='34';
UPDATE static_territories SET tr_name_sk='Južná Európa' WHERE tr_iso_nr='39';
UPDATE static_territories SET tr_name_sk='Juhovýchodná Ázia' WHERE tr_iso_nr='35';
UPDATE static_territories SET tr_name_sk='Západná Afrika' WHERE tr_iso_nr='11';
UPDATE static_territories SET tr_name_sk='Západná Ázia' WHERE tr_iso_nr='145';
UPDATE static_territories SET tr_name_sk='Západná Európa' WHERE tr_iso_nr='155';
UPDATE static_territories SET tr_name_sk='Centrálna Afrika' WHERE tr_iso_nr='17';
UPDATE static_territories SET tr_name_sk='Centrálna Ázia' WHERE tr_iso_nr='143';


UPDATE static_countries SET cn_short_sk='Afganistan' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_sk='Alandské ostrovy' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_sk='Albánsko' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_sk='Alžírsko' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_sk='Americká Samoa' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_sk='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_sk='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_sk='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_sk='Antarktída' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_sk='Antigua a Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_sk='Argentína' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_sk='Arménsko' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_sk='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_sk='Austrália' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_sk='Rakúsko' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_sk='Azerbajdžan' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_sk='Bahrajn' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_sk='Bangladéš' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_sk='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_sk='Bielorusko' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_sk='Belgicko' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_sk='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_sk='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_sk='Bermudy' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_sk='Bhután' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_sk='Bolívia' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_sk='Bosna a Hercegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_sk='Botswana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_sk='Bouvet Island' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_sk='Brazília' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_sk='Britské teritórium v Indickom oceáne' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_sk='Britské Panenské ostrovy' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_sk='Brunej Dar es Salaam' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_sk='Bulharsko' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_sk='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_sk='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_sk='Kambodža' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_sk='Kamerun' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_sk='Kanada' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_sk='Kapverdy' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_sk='Kajmanské ostrovy' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_sk='Stredoafrická republika' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_sk='Čad' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_sk='Čile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_sk='Čína' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_sk='Vianočný ostrov' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_sk='Kokosové ostrovy (Keelingove ostrovy)' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_sk='Kolumbia' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_sk='Komory' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_sk='Demokratická republika Kongo' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_sk='Kongo' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_sk='Cookove ostrovy' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_sk='Kostarika' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_sk='Pobrežie slonoviny' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_sk='Chorvátsko' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_sk='Kuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_sk='Cyprus' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_sk='Česká republika' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_sk='Dánsko' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_sk='Džibuti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_sk='Dominika' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_sk='Dominikánska republika' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_sk='Ekvádor' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_sk='Egypt' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_sk='El Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_sk='Ekvatoriálna Guinea' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_sk='Eritrea' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_sk='Estónsko' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_sk='Etiópia' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_sk='Falklandské ostrovy' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_sk='Faerské ostrovy' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_sk='Fidži' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_sk='Fínsko' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_sk='Francúzsko' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_sk='Francúzska Guyana' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_sk='Francúzska Polynézia' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_sk='Francúzske južné a antarktické oblasti' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_sk='Gabon' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_sk='Gambia' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_sk='Gruzínsko' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_sk='Nemecko' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_sk='Ghana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_sk='Gibraltár' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_sk='Grécko' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_sk='Grónsko' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_sk='Grenada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_sk='Guadeloupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_sk='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_sk='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_sk='Guinea' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_sk='Guinea-Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_sk='Guyana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_sk='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_sk='Heardov a McDonaldov ostrov' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_sk='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_sk='Hong Kong S.A.R., Čína' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_sk='Maďarsko' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_sk='Island' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_sk='India' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_sk='Indonézia' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_sk='Irán' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_sk='Irak' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_sk='Írsko' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_sk='Izrael' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_sk='Taliansko' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_sk='Jamajka' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_sk='Japonsko' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_sk='Jordánsko' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_sk='Kazachstan' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_sk='Keňa' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_sk='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_sk='Kuvajt' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_sk='Kirgistan' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_sk='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_sk='Lotyšsko' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_sk='Libanon' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_sk='Lesotho' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_sk='Libéria' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_sk='Líbya' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_sk='Lichtenštajnsko' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_sk='Litva' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_sk='Luxemburg' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_sk='Macau S.A.R., Čína' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_sk='Macedónsko' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_sk='Madagaskar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_sk='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_sk='Malajzia' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_sk='Maldivy' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_sk='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_sk='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_sk='Marshallove ostrovy' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_sk='Martinik' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_sk='Mauretánia' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_sk='Maurícius' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_sk='Mayotte' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_sk='Mexiko' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_sk='Mikronézia' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_sk='Moldavsko' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_sk='Monako' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_sk='Mongolsko' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_sk='Montserrat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_sk='Maroko' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_sk='Mozambik' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_sk='Myanmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_sk='Namíbia' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_sk='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_sk='Nepál' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_sk='Holandsko' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_sk='Holandské Antily' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_sk='Nová Kaledónia' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_sk='Nový Zéland' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_sk='Nikaragua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_sk='Niger' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_sk='Nigéria' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_sk='Niue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_sk='Norfolk Island' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_sk='Kórejská ľudovodemokratická republika' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_sk='Severné Mariany' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_sk='Nórsko' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_sk='Omán' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_sk='Pakistan' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_sk='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_sk='Palestínske oblasti' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_sk='Panama' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_sk='Papua-Nová Guinea' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_sk='Paraguaj' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_sk='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_sk='Filipíny' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_sk='Pitcairn' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_sk='Poľsko' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_sk='Portugalsko' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_sk='Porto Rico' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_sk='Katar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_sk='Réunion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_sk='Rumunsko' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_sk='Rusko' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_sk='Rwanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_sk='Svätá Helena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_sk='Svätý Krištof a Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_sk='Svätá Lucia' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_sk='Svätý Pierre a Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_sk='Svätý Vincent a Grenadíny' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_sk='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_sk='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_sk='Svätý Tomáš a Princov ostrov' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_sk='Saudská Arábia' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_sk='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_sk='Srbsko' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_sk='Seychely' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_sk='Sierra Leone' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_sk='Singapur' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_sk='Slovenská republika' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_sk='Slovinsko' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_sk='Šalamúnove ostrovy' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_sk='Somálsko' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_sk='Južná Afrika' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_sk='Južná Georgia a Južné Sandwichove ostrovy' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_sk='Kórejská republika' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_sk='Španielsko' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_sk='Sri Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_sk='Sudán' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_sk='Surinam' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_sk='Svalbard a Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_sk='Svazijsko' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_sk='Švédsko' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_sk='Švajčiarsko' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_sk='Sýria' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_sk='Tchaj-wan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_sk='Tadžikistan' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_sk='Tanzánia' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_sk='Thajsko' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_sk='Bahamy' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_sk='Východný Timor' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_sk='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_sk='Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_sk='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_sk='Trinidad a Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_sk='Tunisko' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_sk='Turecko' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_sk='Turkmenistan' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_sk='Turks a Caicos ostrovy' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_sk='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_sk='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_sk='Ukrajina' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_sk='Spojené arabské emiráty' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_sk='Spojené kráľovstvo' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_sk='Spojené štáty' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_sk='Americká Oceánia' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_sk='Uruguaj' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_sk='Americké Panenské ostrovy' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_sk='Uzbekistan' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_sk='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_sk='Vatikán' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_sk='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_sk='Vietnam' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_sk='Wallis a Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_sk='Západná Sahara' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_sk='Jemen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_sk='Zambia' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_sk='Zimbabwe' WHERE cn_iso_2='ZW';
